export enum Events {
  RoomAddMessage = 'room:add:message',
  RoomGetMessages = 'rooms:get:messages',
  RoomGetNewMessage = 'rooms:get:new:message',
  RoomsGet = 'rooms:get',
  RoomGet = 'room:get',
  RoomCreate = 'room:create',
  RoomDefault = 'room:default',
  RoomJoin = 'room:join',
  RoomJoined = 'room:joined',
  RoomAddDrawLine = 'room:add:drawLine',
  RoomGetDrawLines = 'room:get:drawLines',
  RoomClearDraw = 'room:clear:draw',
  ServerGetEvents = 'server:get:events',
  ServerGetIsReady = 'server:get:isReady',
  UsersGet = 'users:get',
  UserGet = 'user:get',
  UserLogin = 'user:login',
  UserName = 'user:name',
  AlertNew = 'alert:new'
}
